### ISSUE TITLE
Add CI to push to DockerHub

### ISSUE THREAD

**Issue by qwelyt** [roipoussiere/cadquery-server#26]
As there now is a Dockerfile that can be built, create a CI-action to automagically build and push to dockerhub when a release is made and when things are merged into `main`

* Action to always build `latest` on updates  to `main`
* Action to tag containers with release versions (like `0.2.3` etc)

This makes takes away the manual process of updating the DockerHub image.

**Comment by roipoussiere** [comment]
I agree with the idea, but with some additional suggestions:

> when things are merged into main

The action should be triggered only when a tagged commit is pushed on main, this way the built version will be more stable. Because typically bugs appears on main and fixed before publishing a new release. I don't have yet a suite test to check the project stability before each push on main.

The action could also publish the project on PyPI.

Would you like to work on this?

**Comment by roipoussiere** [comment]
Note that this repository is mirrored with https://framagit.org/roipoussiere/cadquery-server and CI could eventually be performed here, using a `.gitlab-ci.yml`.

**Comment by roipoussiere** [comment]
PR merged: #42

But CI failed: https://github.com/roipoussiere/cadquery-server/actions/runs/3070866018/jobs/4961023286

**Comment by roipoussiere** [comment]
fixed in 5234ffd and 48f48a8
thanks for your contribution @qwelyt :)
